Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.ChitChat: true

Sitegeist:
  ChitChat:

    # the dictionary and probability to use if nothing else is specified
    defaults:
      dictionary: pseudoLatin
      probability: predictable

    # providers for random numbers
    probablility:
      predictable: 'Sitegeist\ChitChat\Domain\PredictableProbabilityProvider'
      random: 'Sitegeist\ChitChat\Domain\RandomProbabilityProvider'

    # dictionaries
    dictionaries:
      pseudoLatin: 'Sitegeist\ChitChat\Domain\PseudoLatinDictionaryProvider'

